[package]
name = "foresyn-backend"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
axum.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tower.workspace = true
